name: Update BM digital contacts for Anytone 878

on:
  schedule:
      - cron: '0 22 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Requirements
        run: pip3 install -r requirements.txt

      - name: Generate BM digital contacts for whole world
        run: |
          python3 jtc_users.py


      - name: Generate BM digital contacts for Ukraine
        run: |
          python3 jtc_users.ua.py


      - name: Generate BM digital contacts for RB 
        run: |
          python3 jtc_users.by.py
          
          
#      - name: 'Get pandoc'
#        run:  sudo apt-get install pandoc
    
#      - name: 'Get My TODO List'
#        run:  pandoc ./cv.md > index.html
  
#      - name: html to pdf
#        uses: fifsky/html-to-pdf-action@master
#        with:
#          htmlFile: index.html
#          outputFile: resume.pdf
#          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

      - name: Create directory listing 
        run: tree -P "*.csv" -H '.' --charset utf-8 > index.html
               
      - name: setup git config
        run: |
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.EMAIL }}

      - name: commit changes
        run: |
          chmod +x ./acommit.sh
          ./acommit.sh
          
           
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: Github Actions job result ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # Literal body:
          # body: Build job of ${{github.repository}} completed successfully!
          body: Build job of ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # Read file contents as body:
          # body: file://README.md
          to: shaposhnikoff@gmail.com ,max@shaposhnikoff.info
          from: Maksym Shaposhnikov # <user@example.com>
          # Optional carbon copy recipients
          content_type: text/html
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
